version: '3.8'

services:
  db:
    image: postgres:16 # Use a specific version of PostgreSQL
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: quanlybanthanhnien
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data # Mount a named volume for data persistence
    ports:
      - "5433:5433" # Expose PostgreSQL port to the host

volumes:
  postgres_data: # Define the named volume